services:
    app:
      image: sciabarracom/mastrogpt-starter:2501052000
      volumes:
        - ../..:/workspaces:cached
      command: sleep inf
      depends_on:
        - redis
        - etcd
        - minio
        - milvus
    redis:
        #image: redis:latest
        image: bitnami/valkey:7.2.5
        ports:
          - "6379:6379"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
    etcd:
      image: quay.io/coreos/etcd:v3.5.14
      #image: bitnami/etcd:3.5.17-debian-12-r0
      environment:
        - ETCD_AUTO_COMPACTION_MODE=revision
        - ETCD_AUTO_COMPACTION_RETENTION=1000
        - ETCD_QUOTA_BACKEND_BYTES=4294967296
        - ETCD_SNAPSHOT_COUNT=50000
      volumes:
        - etcd:/etcd
      command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
      healthcheck:
        test: ["CMD", "etcdctl", "endpoint", "health"]
        interval: 30s
        timeout: 20s
        retries: 3
    minio:
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        #image: bitnami/minio:2023.3.24
        environment:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        ports:
          - "9001:9001"
          - "9000:9000"
        volumes:
          - minio:/minio_data
        command: minio server /minio_data --console-address ":9001"
    milvus:
      image: milvusdb/milvus:v2.5.2
      command: ["milvus", "run", "standalone"]
      security_opt:
      - seccomp:unconfined
      environment:
        ETCD_ENDPOINTS: etcd:2379
        MINIO_ADDRESS: minio:9000
      volumes:
        - milvus:/var/lib/milvus
      ports:
        - "19530:19530"
        - "9091:9091"
      depends_on:
        - "etcd"
        - "minio"
networks:
  default:
    name: mastrogpt
volumes:
  etcd:
  milvus:
  minio: